import { redirect } from "next/navigation";
import { auth } from "@/auth";
import { prisma } from "@/lib/prisma";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table";
import { CompensationExportForm } from "@/components/compensation-export-form";

export default async function CompensationExportPage() {
  const session = await auth();
  if (session?.user?.role !== "HR_ADMIN") {
    redirect("/");
  }

  const history = await prisma.bankTransferExport.findMany({
    include: { generatedBy: { select: { email: true } } },
    orderBy: { createdAt: "desc" },
    take: 20,
  });

  return (
    <div className="space-y-6">
      <div>
        <h1 className="text-2xl font-bold">Bank transfer export</h1>
        <p className="text-muted-foreground">
          Generates a generic Excel file (net amount per active employee) for a given
          month. Column layout will be adjusted once the bank&apos;s exact format is known.
        </p>
      </div>

      <CompensationExportForm />

      <Card>
        <CardHeader>
          <CardTitle className="text-base">Export history</CardTitle>
        </CardHeader>
        <CardContent className="p-0">
          <Table>
            <TableHeader>
              <TableRow>
                <TableHead>Date generated</TableHead>
                <TableHead>Period</TableHead>
                <TableHead>Employees</TableHead>
                <TableHead>Total amount</TableHead>
                <TableHead>Generated by</TableHead>
              </TableRow>
            </TableHeader>
            <TableBody>
              {history.map((h) => (
                <TableRow key={h.id}>
                  <TableCell>{new Date(h.createdAt).toLocaleString()}</TableCell>
                  <TableCell>
                    {h.periodYear}-{String(h.periodMonth).padStart(2, "0")}
                  </TableCell>
                  <TableCell>{h.employeeCount}</TableCell>
                  <TableCell>{h.totalAmount.toLocaleString(undefined, { maximumFractionDigits: 2 })}</TableCell>
                  <TableCell>{h.generatedBy?.email ?? "—"}</TableCell>
                </TableRow>
              ))}
              {history.length === 0 && (
                <TableRow>
                  <TableCell colSpan={5} className="text-center text-muted-foreground">
                    No exports yet.
                  </TableCell>
                </TableRow>
              )}
            </TableBody>
          </Table>
        </CardContent>
      </Card>
    </div>
  );
}
